version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
      - npm i -g serverless@3
      - npm i
  build:
    on-failure: ABORT
    commands:
      - npm test
      - serverless deploy --stage dev
artifacts:
  files:
    - my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'node_modules/**/*'
